version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    target-branch: 'develop'
    reviewers:
      - 'Whamo12'
      - 'skewled'

  - package-ecosystem: 'npm'
    directory: '/frontend'
    schedule:
      interval: 'daily'
    target-branch: 'develop'
    reviewers:
      - 'Whamo12'
      - 'skewled'
